# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eccdf5c78fe4c14231f9277c75d2fa24fdbd6d6067d8220459339828fbd48a1d2046fe360c6d8898f19970920960de6b54277fbd432651ee008e49392fbfcdf

test:
  secret_key_base: 95b591e08997c680824b214c99671de7a77f13bb4e0bc63f36d31dba9a7bea77def0b024097c87826227bcdbc955267ea245d18c57e53ddef1b3f169890bcac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
